const STORAGE_KEY="estadisticas_nexus_docs_v1";
const ALL_SHEETS=["USD","CUP","RUDY","YAMI","YOEL","OSMEL","ALEJANDRO","CHARLY","YAN CARLOS","ALVARO","ALIET","MALENA","KENNY","BABY","ALEX","ELY","MARBELIS","MANUEL","EDDY","ANELYS","Copia de ANELYS","LEO","FELIX","Copia de JAVIER-USD"];
const WORKER_SHEETS=ALL_SHEETS.filter(s=>s!=="USD"&&s!=="CUP");
const CURRENCIES=[["USA","USD"],["EUR","EUR"],["MXC","MXC"],["CAD","CAD"],["REAL","REAL"]];
let docs=[];try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]");if(Array.isArray(saved))docs=saved;}catch(e){}
let state={view:"home",current:null,rows:null,summary:{},loading:{},filters:{}};
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(docs));}
function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function money(n){return Number(n||0).toLocaleString("es-MX",{maximumFractionDigits:2});}
function extractId(url){const m=String(url||"").match(/\/spreadsheets\/d\/([a-zA-Z0-9-_]+)/);return m?m[1]:"";}
function parseAmount(v){if(typeof v==="number")return Number.isFinite(v)?v:0;let s=String(v??"").trim().replace(/\s/g,"").replace(/[^0-9,.-]/g,"");if(!s)return 0;if(s.includes(",")&&s.includes("."))s=s.lastIndexOf(",")>s.lastIndexOf(".")?s.replace(/\./g,"").replace(",","."):s.replace(/,/g,"");else if(s.includes(",")){const p=s.split(",");s=(p.length===2&&p[1].length<=2)?p[0].replace(/\./g,"")+"."+p[1]:s.replace(/,/g,"");}const n=Number(s);return Number.isFinite(n)?n:0;}
function parseDateDMY(v){const p=String(v||"").trim().split("/");if(p.length!==3)return null;const d=+p[0],m=+p[1],y=+p[2];if(!d||!m||!y)return null;const dt=new Date(y,m-1,d);return Number.isNaN(dt.getTime())?null:dt;}
function parseCSV(text){const rows=[];let row=[],cell="",q=false;for(let i=0;i<text.length;i++){const c=text[i];if(q){if(c==='"'&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')q=false;else cell+=c;}else{if(c==='"')q=true;else if(c===','){row.push(cell);cell="";}else if(c==='\n'){row.push(cell.replace(/\r$/,""));rows.push(row);row=[];cell="";}else cell+=c;}}if(cell.length||row.length){row.push(cell.replace(/\r$/,""));rows.push(row);}return rows;}
async function fetchSheetRows(doc,sheet){const id=extractId(doc.url);if(!id)throw new Error("Enlace no válido");const url="https://docs.google.com/spreadsheets/d/"+encodeURIComponent(id)+"/gviz/tq?tqx=out:csv&sheet="+encodeURIComponent(sheet);const r=await fetch(url,{cache:"no-store"});if(!r.ok)throw new Error("Google respondió "+r.status);const text=await r.text();if(/<!doctype html|<html/i.test(text)||/sign in|iniciar sesi[oó]n/i.test(text))throw new Error("El documento no tiene acceso por enlace");return parseCSV(text);}
function defaultFilter(docId){if(!state.filters[docId])state.filters[docId]={sheet:ALL_SHEETS[0],from:"2026-07-01",to:"2026-07-04",currency:"USA"};return state.filters[docId];}
function route(view,docId,push=true){const doc=docId?docs.find(d=>d.id===docId):null;state.view=view;state.current=doc||null;if(view!=="result")state.rows=view==="query"?state.rows:null;if(push)history.pushState({nexus:true,view,docId:doc?.id||null},"",location.href);render();if(doc&&(view==="general"||view==="individual")&&!state.summary[doc.id]&&!state.loading[doc.id])loadSummary(doc);}
function applyHistory(h){const view=h?.nexus?h.view:"home",doc=h?.docId?docs.find(d=>d.id===h.docId):null;state.view=doc||["home","add"].includes(view)?view:"home";state.current=doc||null;if(state.view!=="result")state.rows=state.view==="query"?state.rows:null;render();if(doc&&(state.view==="general"||state.view==="individual")&&!state.summary[doc.id]&&!state.loading[doc.id])loadSummary(doc);}
window.addEventListener("popstate",e=>applyHistory(e.state));
history.replaceState({nexus:true,view:"home",docId:null},"",location.href);
function render(){const app=document.getElementById("app");if(["home","add","menu","edit"].includes(state.view))app.innerHTML=homeHtml()+overlayHtml();else if(state.view==="general"||state.view==="individual")app.innerHTML=statsPageHtml(state.view);else app.innerHTML=queryPageHtml();}
function currencyHtml(doc){const summary=state.summary[doc.id],loading=state.loading[doc.id];return CURRENCIES.map(([code,label],i)=>{const value=summary?.totals?.[code],cls=i===4?"currency-box wide":"currency-box";return '<div class="'+cls+'"><div class="currency-label">'+label+'</div><div class="currency-value'+(loading?' loading':'')+'">'+(loading?'Calculando…':summary?.error?'—':money(value||0))+'</div></div>';}).join("");}
function homeHtml(){const cards=docs.length?'<div class="docs-grid">'+docs.map(doc=>{const summary=state.summary[doc.id];return '<article class="doc-card" data-open="'+esc(doc.id)+'"><div class="doc-top"><div class="doc-title-wrap"><h3 class="doc-title">'+esc(doc.name)+'</h3><div class="doc-kicker"><span class="dot"></span><span>Resumen mensual · todas las hojas</span></div></div></div><div class="currency-grid">'+currencyHtml(doc)+'</div><div class="card-foot"><span class="'+(summary?.error?'status-error':'status-ok')+'">'+(state.loading[doc.id]?'Actualizando totales…':summary?.error?'No se pudo leer el documento':'Totales del documento')+'</span><span>•••</span></div></article>';}).join("")+'</div>':'<div class="empty"><div class="empty-icon">∑</div><h2>Aún no hay documentos</h2><p>Agrega tu primer Google Spreadsheet para comenzar a consultar estadísticas y ver los acumulados mensuales por moneda.</p><button class="btn btn-blue" id="emptyAddBtn">Agregar documento</button></div>';return '<div class="app-shell"><header class="hero"><div class="hero-inner"><div class="brand"><div class="brand-mark">N</div><div class="brand-copy"><h1>Estadísticas Nexus</h1><p>Resumen y consulta de operaciones</p></div></div><button class="btn btn-primary" id="addBtn">+ Agregar documento</button></div></header><main class="main"><div class="section-head"><div><h2 class="section-title">Documentos</h2><div class="section-sub">'+docs.length+' '+(docs.length===1?'documento':'documentos')+' en este dispositivo</div></div></div>'+cards+'</main></div>';}
function overlayHtml(){if(state.view==="add")return addModalHtml();if(state.view==="menu")return menuHtml();if(state.view==="edit")return editModalHtml();return "";}
function addModalHtml(){return '<div class="modal-bg" id="modalBg"><div class="modal-card"><div class="modal-head"><h2>Agregar documento</h2><button class="btn-icon" data-close>×</button></div><div class="field"><label>Nombre</label><input id="docName" placeholder="Ej. Julio 2026"></div><div class="field"><label>Enlace de Google Sheets</label><input id="docUrl" placeholder="https://docs.google.com/spreadsheets/d/..."></div><div class="note">El documento se guardará solamente en este dispositivo.</div><div class="modal-actions"><button class="btn btn-soft" data-close>Cancelar</button><button class="btn btn-blue" id="saveBtn">Guardar</button></div></div></div>';}
function editModalHtml(){const d=state.current;return '<div class="modal-bg" id="modalBg"><div class="modal-card"><div class="modal-head"><h2>Editar documento</h2><button class="btn-icon" data-close>×</button></div><div class="field"><label>Nombre</label><input id="editName" value="'+esc(d?.name||"")+'"></div><div class="field"><label>Enlace de Google Sheets</label><input id="editUrl" value="'+esc(d?.url||"")+'"></div><div class="modal-actions"><button class="btn btn-soft" data-close>Cancelar</button><button class="btn btn-blue" id="saveEditBtn">Guardar cambios</button></div></div></div>';}
function menuHtml(){const d=state.current;if(!d)return "";return '<div class="sheet-bg" id="sheetBg"><div class="bottom-sheet"><div class="sheet-handle"></div><div class="sheet-title"><h3>'+esc(d.name)+'</h3><p>Selecciona una opción</p></div><button class="sheet-option" data-action="edit"><span class="sheet-icon">✎</span><span><strong>Editar</strong><span>Cambiar nombre o enlace del documento</span></span></button><button class="sheet-option" data-action="general"><span class="sheet-icon">∑</span><span><strong>Estadísticas generales</strong><span>Totales y promedio por moneda</span></span></button><button class="sheet-option" data-action="individual"><span class="sheet-icon">≡</span><span><strong>Estadísticas individuales</strong><span>Totales y promedios por trabajador</span></span></button><button class="sheet-option" data-action="query"><span class="sheet-icon">⌕</span><span><strong>Consulta</strong><span>Filtrar por hoja, fecha y moneda</span></span></button><button class="sheet-option danger" data-action="delete"><span class="sheet-icon">⌫</span><span><strong>Eliminar</strong><span>Quitar este documento del dispositivo</span></span></button></div></div>';}
function pageHeader(subtitle){const d=state.current;return '<header class="detail-hero"><div class="detail-inner"><div class="back" id="backBtn">← Atrás</div><div class="detail-title"><div class="brand-mark">N</div><div><h1>'+esc(d?.name||"")+'</h1><p>'+esc(subtitle)+'</p></div></div></div></header>';}
function statsPageHtml(type){const d=state.current,s=state.summary[d?.id];let body;if(state.loading[d?.id]||!s)body='<div class="stats-card"><div class="loading-block">Calculando estadísticas…</div></div>';else if(s.error)body='<div class="stats-card"><div class="loading-block status-error">No se pudieron leer las hojas del documento.</div></div>';else body=type==="general"?generalStatsHtml(s):individualStatsHtml(s);return '<div class="app-shell">'+pageHeader(type==="general"?'Estadísticas generales':'Estadísticas por trabajador')+'<main class="main">'+body+'</main></div>';}
function generalStatsHtml(s){return '<div class="stats-card"><p class="stats-note">El promedio corresponde al monto medio por operación de cada moneda en todas las hojas de trabajadores.</p><div class="stat-currency-grid">'+CURRENCIES.map(([code,label])=>{const total=s.totals[code]||0,count=s.counts[code]||0,avg=count?total/count:0;return '<div class="stat-currency"><h3>'+label+'</h3><div class="stat-row"><span>Total</span><strong>'+money(total)+'</strong></div><div class="stat-row"><span>Operaciones</span><strong>'+count+'</strong></div><div class="stat-row"><span>Promedio</span><strong>'+money(avg)+'</strong></div></div>';}).join("")+'</div></div>';}
function individualStatsHtml(s){const headers=CURRENCIES.map(([,label])=>'<th>'+label+' total</th><th>'+label+' prom.</th>').join("");const rows=WORKER_SHEETS.map(name=>{const w=s.workers[name];if(!w)return "";const cells=CURRENCIES.map(([code])=>{const total=w.totals[code]||0,count=w.counts[code]||0;return '<td>'+money(total)+'</td><td>'+money(count?total/count:0)+'</td>';}).join("");return '<tr><td class="worker-name">'+esc(name)+'</td>'+cells+'</tr>';}).join("");return '<div class="stats-card"><p class="stats-note">Cada fila corresponde a una hoja/trabajador. Se muestra el total y el promedio por operación de cada moneda.</p><div class="table-wrap"><table><thead><tr><th>Trabajador</th>'+headers+'</tr></thead><tbody>'+rows+'</tbody></table></div></div>';}
