'use strict';

const STORAGE_KEY='estadisticas_nexus_docs_v1';
const SUMMARY_KEY='estadisticas_nexus_summary_v1';
const CURRENCIES=[['USA','USD'],['EUR','EUR'],['MXC','MXC'],['CAD','CAD'],['REAL','REAL']];
const CHART_CURRENCIES=[['USA','USD'],['EUR','EUR'],['MXC','MEX'],['CAD','CAD'],['REAL','REAL']];
const NEXUS_LOGO='<img class="nexus-app-logo" src="./app-icon.svg?v=nexus-stats-20260816" alt="Nexus Stats">';

let docs=[];
let state={view:'home',current:null,rows:null,summary:{},loading:{},filters:{},homeChartCurrency:'USA'};
let manualRefreshing=false;
let reloadRefreshing=false;

function loadLocalState(){
  try{
    const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');
    if(Array.isArray(saved))docs=saved.map(d=>({...d,name:String(d?.name||'').trim(),locked:!!d?.locked}));
  }catch(e){docs=[];}
  try{
    const cached=JSON.parse(localStorage.getItem(SUMMARY_KEY)||'{}');
    if(cached&&typeof cached==='object'&&!Array.isArray(cached))state.summary=cached;
  }catch(e){state.summary={};}
}
function saveDocs(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(docs));}catch(e){}}
function saveSummary(){try{localStorage.setItem(SUMMARY_KEY,JSON.stringify(state.summary||{}));}catch(e){}}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function money(n){return Number(n||0).toLocaleString('es-MX',{maximumFractionDigits:2});}
function extractId(url){const m=String(url||'').match(/\/spreadsheets\/d\/([a-zA-Z0-9-_]+)/);return m?m[1]:'';}
function parseAmount(v){if(typeof v==='number')return Number.isFinite(v)?v:0;let s=String(v??'').trim().replace(/\s/g,'').replace(/[^0-9,.-]/g,'');if(!s)return 0;if(s.includes(',')&&s.includes('.'))s=s.lastIndexOf(',')>s.lastIndexOf('.')?s.replace(/\./g,'').replace(',','.'):s.replace(/,/g,'');else if(s.includes(',')){const p=s.split(',');s=(p.length===2&&p[1].length<=2)?p[0].replace(/\./g,'')+'.'+p[1]:s.replace(/,/g,'');}const n=Number(s);return Number.isFinite(n)?n:0;}
function parseDateDMY(v){const p=String(v||'').trim().split('/');if(p.length!==3)return null;const d=+p[0],m=+p[1],y=+p[2];if(!d||!m||!y)return null;const dt=new Date(y,m-1,d);return Number.isNaN(dt.getTime())?null:dt;}
function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(q){if(c==='"'&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')q=false;else cell+=c;}else{if(c==='"')q=true;else if(c===','){row.push(cell);cell='';}else if(c==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell='';}else cell+=c;}}if(cell.length||row.length){row.push(cell.replace(/\r$/,''));rows.push(row);}return rows;}
function checkboxValueIsChecked(v){if(v===true||v===1)return true;if(v===false||v===0||v==null)return false;const s=String(v).trim().toLocaleUpperCase('es-MX');return s==='TRUE'||s==='VERDADERO'||s==='1'||s==='SI'||s==='SÍ';}
function firstDateInRows(rows){for(const row of rows){const d=parseDateDMY(row[0]);if(d)return d;}return null;}
function monthDaysFromDate(d){return d?new Date(d.getFullYear(),d.getMonth()+1,0).getDate():0;}
function rounded(n){return Math.round((Number(n||0)+Number.EPSILON)*100)/100;}
function isHtmlOrLogin(text,type=''){return type.includes('text/html')||/<!doctype html|<html/i.test(text)||/sign in|iniciar sesi[oó]n|request access|solicitar acceso/i.test(text);}

async function timedFetch(url,options={},timeoutMs=15000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{return await fetch(url,{...options,signal:controller.signal});}catch(e){if(e?.name==='AbortError')throw new Error('El documento tardó demasiado en responder');throw e;}finally{clearTimeout(timer);}}
async function fetchSheetRows(doc,sheet){const id=extractId(doc.url);if(!id)throw new Error('Enlace no válido');const url='https://docs.google.com/spreadsheets/d/'+encodeURIComponent(id)+'/gviz/tq?tqx=out:csv&sheet='+encodeURIComponent(sheet)+'&range=A:D&_='+Date.now();const r=await timedFetch(url,{cache:'no-store'},20000);if(!r.ok)throw new Error('Google respondió '+r.status);const type=(r.headers.get('content-type')||'').toLowerCase(),text=await r.text();if(isHtmlOrLogin(text,type))throw new Error('El documento no tiene acceso por enlace');return parseCSV(text);}
async function readSheetU1(doc,sheet){const id=extractId(doc.url);if(!id)throw new Error('Enlace no válido');const url='https://docs.google.com/spreadsheets/d/'+encodeURIComponent(id)+'/gviz/tq?tqx=out:csv&headers=0&range=U1:U1&sheet='+encodeURIComponent(sheet)+'&_='+Date.now();const r=await timedFetch(url,{cache:'no-store'},10000);if(!r.ok)throw new Error('No se pudo comprobar U1 de '+sheet);const type=(r.headers.get('content-type')||'').toLowerCase(),text=await r.text();if(isHtmlOrLogin(text,type))throw new Error('El documento no tiene acceso mediante vínculo');const rows=parseCSV(text);return checkboxValueIsChecked(rows?.[0]?.[0]);}
async function spreadsheetIsPublic(url){const id=extractId(url);if(!id)return false;try{const endpoint='https://docs.google.com/spreadsheets/d/'+encodeURIComponent(id)+'/gviz/tq?tqx=out:json&headers=0&range=A1:A1&_='+Date.now();const r=await timedFetch(endpoint,{cache:'no-store'},10000);if(!r.ok)return false;const type=(r.headers.get('content-type')||'').toLowerCase(),text=await r.text();if(isHtmlOrLogin(text,type))return false;const start=text.indexOf('{'),end=text.lastIndexOf('}');if(start<0||end<=start)return false;const payload=JSON.parse(text.slice(start,end+1));return !payload.status||payload.status==='ok';}catch(e){return false;}}
async function mapLimit(items,limit,fn){const result=new Array(items.length);let cursor=0;async function worker(){while(true){const i=cursor++;if(i>=items.length)return;result[i]=await fn(items[i],i);}}await Promise.all(Array.from({length:Math.min(limit,items.length||1)},worker));return result;}
async function discoverWorkbookSheets(doc){const id=extractId(doc.url);if(!id)throw new Error('Enlace no válido');if(!window.XLSX)throw new Error('No se pudo cargar el lector de Google Sheets');const exportUrl='https://docs.google.com/spreadsheets/d/'+encodeURIComponent(id)+'/export?format=xlsx&_='+Date.now();const response=await timedFetch(exportUrl,{cache:'no-store'},25000);if(!response.ok)throw new Error('No se pudo leer la estructura del documento');const type=(response.headers.get('content-type')||'').toLowerCase();if(type.includes('text/html'))throw new Error('El documento no tiene acceso mediante vínculo');let workbook;try{workbook=XLSX.read(await response.arrayBuffer(),{bookSheets:true,bookProps:false});}catch(e){throw new Error('No se pudo leer la lista de hojas del documento');}const names=Array.isArray(workbook.SheetNames)?workbook.SheetNames:[];const checks=await mapLimit(names,8,async name=>{try{return {name,enabled:await readSheetU1(doc,name)};}catch(e){return {name,enabled:false,error:e};}});if(names.length&&checks.every(x=>x.error))throw checks[0].error||new Error('No se pudieron comprobar las hojas del documento');return checks;}
async function summarizeActiveSheet(doc,sheet){const rows=await fetchSheetRows(doc,sheet);const totals={USA:0,EUR:0,MXC:0,CAD:0,REAL:0};for(const row of rows){const code=String(row[1]||'').trim().toUpperCase(),raw=row[2];if(!Object.prototype.hasOwnProperty.call(totals,code)||raw==null||String(raw).trim()==='')continue;totals[code]+=parseAmount(raw);}Object.keys(totals).forEach(k=>totals[k]=rounded(totals[k]));return {name:sheet,totals,monthDate:firstDateInRows(rows)};}
async function loadSummary(doc,{force=false}={}){if(!doc||(!force&&doc.locked)||state.loading[doc.id])return;state.loading[doc.id]=true;render();const totals={USA:0,EUR:0,MXC:0,CAD:0,REAL:0},workers={},sheetNames=[];try{const workbookSheets=await discoverWorkbookSheets(doc),active=workbookSheets.filter(x=>x.enabled).map(x=>x.name),results=await mapLimit(active,4,async sheet=>{try{return await summarizeActiveSheet(doc,sheet);}catch(e){return {name:sheet,error:e};}});let monthDate=null;for(const item of results){if(!item||item.error)continue;sheetNames.push(item.name);workers[item.name]={totals:item.totals};if(!monthDate&&item.monthDate)monthDate=item.monthDate;for(const code of Object.keys(totals))totals[code]+=item.totals[code]||0;}Object.keys(totals).forEach(k=>totals[k]=rounded(totals[k]));const daysInMonth=monthDaysFromDate(monthDate);state.summary[doc.id]={totals,workers,sheetNames,daysInMonth,month:monthDate?monthDate.getMonth()+1:null,year:monthDate?monthDate.getFullYear():null,error:false};}catch(e){state.summary[doc.id]={totals,workers,sheetNames,daysInMonth:0,error:true,errorMessage:e?.message||String(e)};}finally{state.loading[doc.id]=false;saveSummary();syncFilterForDoc(doc.id);render();}}
async function refreshAllDocuments(){if(manualRefreshing)return;manualRefreshing=true;render();try{for(const doc of docs){if(!doc.locked)await loadSummary(doc);}}finally{manualRefreshing=false;render();}}

function defaultFilter(docId){const actual=state.summary[docId]?.sheetNames||[];if(!state.filters[docId])state.filters[docId]={sheet:actual[0]||'',from:'2026-07-01',to:'2026-07-04',currency:'USA'};syncFilterForDoc(docId);return state.filters[docId];}
function syncFilterForDoc(docId){const f=state.filters[docId];if(!f)return;const actual=state.summary[docId]?.sheetNames||[];if(actual.length&&!actual.includes(f.sheet))f.sheet=actual[0];if(!actual.length)f.sheet='';}
function syncFilterInputs(){const d=state.current;if(!d)return null;const f=defaultFilter(d.id);for(const id of ['sheet','from','to','currency']){const el=document.getElementById(id);if(el)f[id]=el.value;}return f;}
async function doFilter(){const d=state.current,f=syncFilterInputs();if(!d||!f||!f.sheet)return;if(!f.from||!f.to){alert('Selecciona las dos fechas.');return;}const start=new Date(f.from+'T00:00:00'),end=new Date(f.to+'T23:59:59');if(start>end){alert('La fecha inicial no puede ser posterior a la fecha final.');return;}const btn=document.getElementById('filterBtn');try{if(btn){btn.disabled=true;btn.textContent='Consultando…';}const rows=await fetchSheetRows(d,f.sheet);let inherited=null;const items=[];rows.forEach((row,index)=>{const detected=parseDateDMY(row[0]);if(detected)inherited=String(row[0]).trim();if(!inherited)return;const code=String(row[1]||'').trim().toUpperCase(),raw=row[2],name=String(row[3]||'').trim();if((raw==null||String(raw).trim()==='')&&!name)return;const date=parseDateDMY(inherited);if(!date||date<start||date>end||code!==f.currency)return;items.push({row:index+1,date:inherited,currency:code,amount:parseAmount(raw),name});});const total=rounded(items.reduce((s,x)=>s+x.amount,0));state.rows={sheet:f.sheet,currency:f.currency,from:f.from,to:f.to,count:items.length,total,items};route('result',d.id,true);}catch(e){alert('No se pudo consultar el Spreadsheet. '+(e?.message||e));}finally{const b=document.getElementById('filterBtn');if(b){b.disabled=false;b.textContent='Filtrar';}}}

function route(view,docId,push=true){const previous=state.view,doc=docId?docs.find(d=>d.id===docId):null;state.view=view;state.current=doc||null;if(view!=='result')state.rows=view==='query'?state.rows:null;if(push){const payload={nexus:true,view,docId:doc?.id||null},replaceFromMenu=previous==='menu'&&['edit','general','individual','query','delete-confirm'].includes(view);if(replaceFromMenu)history.replaceState(payload,'',location.href);else history.pushState(payload,'',location.href);}render();}
function goHomeReplace(){state.view='home';state.current=null;state.rows=null;history.replaceState({nexus:true,view:'home',docId:null},'',location.href);render();}
function applyHistory(h){const view=h?.nexus?h.view:'home',doc=h?.docId?docs.find(d=>d.id===h.docId):null;state.view=doc||['home','add'].includes(view)?view:'home';state.current=doc||null;if(state.view!=='result')state.rows=state.view==='query'?state.rows:null;render();}

function lockIcon(locked){return locked?'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 10V7a5 5 0 0 1 10 0v3"/><rect x="5" y="10" width="14" height="11" rx="3"/><path d="M12 14v3"/></svg>':'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 10V7a5 5 0 0 1 9.6-2"/><rect x="5" y="10" width="14" height="11" rx="3"/><path d="M12 14v3"/></svg>';}
function lockButton(doc){const locked=!!doc.locked,label=locked?'Bloqueado':'Abierto';return '<button class="doc-lock '+(locked?'is-locked':'is-unlocked')+'" data-doc-lock="'+esc(doc.id)+'" type="button" aria-pressed="'+(locked?'true':'false')+'" title="'+(locked?'Desbloquear documento':'Bloquear documento')+'"><span class="doc-lock-icon">'+lockIcon(locked)+'</span><span class="doc-lock-label">'+label+'</span></button>';}
function currencyHtml(doc){const summary=state.summary[doc.id],loading=state.loading[doc.id]||(!doc.locked&&reloadRefreshing);return CURRENCIES.map(([code,label],i)=>{const cls=i===4?'currency-box wide':'currency-box',value=summary?.totals?.[code];return '<div class="'+cls+'"><div class="currency-label">'+label+'</div><div class="currency-value'+(loading?' loading':'')+'">'+(loading?'Actualizando…':summary?.error?'—':money(value||0))+'</div></div>';}).join('');}
function chartHtml(){const code=state.homeChartCurrency||'USA',rows=docs.map(doc=>({label:doc.name,value:Number(state.summary[doc.id]?.totals?.[code]||0)})),loading=manualRefreshing||reloadRefreshing||docs.some(d=>state.loading[d.id]),max=Math.max(1,...rows.map(r=>Math.abs(r.value))),options=CHART_CURRENCIES.map(([v,l])=>'<option value="'+v+'" '+(v===code?'selected':'')+'>'+l+'</option>').join('');const body=loading?'<div class="home-chart-empty">Actualizando gráfico…</div>':!rows.length?'<div class="home-chart-empty">No hay documentos para graficar.</div>':'<div class="home-bars">'+rows.map(r=>{const pct=Math.max(0,Math.min(100,(Math.abs(r.value)/max)*100));return '<div class="home-bar-row"><div class="home-bar-label" title="'+esc(r.label)+'">'+esc(r.label)+'</div><div class="home-bar-track"><div class="home-bar-fill" style="--bar-width:'+pct.toFixed(2)+'%"></div></div><div class="home-bar-value">'+money(r.value)+'</div></div>';}).join('')+'</div>';return '<section class="home-chart-card"><div class="home-chart-head"><div><h2>Comparación por documento</h2><p>Cantidad de la moneda seleccionada en cada documento</p></div><label class="home-chart-selector"><span>Moneda</span><select id="homeChartCurrency">'+options+'</select></label></div>'+body+'</section>';}
function homeHtml(){const cards=docs.length?'<div class="docs-grid">'+docs.map(doc=>{const summary=state.summary[doc.id],status=doc.locked?'Datos bloqueados':state.loading[doc.id]?'Actualizando totales…':summary?.error?'No se pudo leer el documento':'';return '<article class="doc-card '+(doc.locked?'doc-card-locked':'')+'" data-open="'+esc(doc.id)+'">'+lockButton(doc)+'<div class="doc-top"><div class="doc-title-wrap"><h3 class="doc-title">'+esc(doc.name)+'</h3><div class="doc-kicker"><span class="dot"></span><span>Resumen general</span></div></div></div><div class="currency-grid">'+currencyHtml(doc)+'</div><div class="card-foot">'+(status?'<span class="'+(summary?.error?'status-error':'status-ok')+'">'+status+'</span>':'')+'<span>•••</span></div></article>';}).join('')+'</div>':'<div class="empty"><div class="empty-icon">∑</div><h2>Aún no hay documentos</h2><p>Agrega tu primer Google Spreadsheet para comenzar a consultar estadísticas y ver los acumulados mensuales por moneda.</p><button class="btn btn-add" id="emptyAddBtn"><span class="add-icon">+</span><span class="add-label">Agregar documento</span></button></div>';return '<div class="app-shell"><header class="hero"><div class="hero-inner"><div class="brand"><div class="brand-mark brand-mark-logo logo-refresh-control '+(manualRefreshing?'is-refreshing':'')+'" id="refreshAllBtn" role="button" tabindex="0" title="Actualizar todo" aria-label="Actualizar todo">'+NEXUS_LOGO+'</div><div class="brand-copy"><h1>Nexus Stats</h1><p>Resumen y consulta de operaciones</p></div></div><button class="btn btn-add" id="addBtn"><span class="add-icon">+</span><span class="add-label">Agregar documento</span></button></div></header><main class="main"><div class="section-head"><div><h2 class="section-title">Documentos</h2></div></div>'+cards+(docs.length?chartHtml():'')+'</main></div>';}
function addModalHtml(){return '<div class="modal-bg" id="modalBg"><div class="modal-card"><div class="modal-head"><h2>Agregar documento</h2><button class="btn-icon" data-close>×</button></div><div class="field"><label>Nombre</label><input id="docName" placeholder="Nombre" autocapitalize="sentences"></div><div class="field"><label>Enlace de Google Sheets</label><input id="docUrl" placeholder="Pega aquí el enlace de Google Sheets"></div><div class="modal-actions"><button class="btn btn-soft" data-close>Cancelar</button><button class="btn btn-blue" id="saveBtn">Guardar</button></div></div></div>';}
function editModalHtml(){const d=state.current;return '<div class="modal-bg" id="modalBg"><div class="modal-card"><div class="modal-head"><h2>Editar documento</h2><button class="btn-icon" data-close>×</button></div><div class="field"><label>Nombre</label><input id="editName" value="'+esc(d?.name||'')+'" autocapitalize="sentences"></div><div class="field"><label>Enlace de Google Sheets</label><input id="editUrl" value="'+esc(d?.url||'')+'"></div><div class="modal-actions"><button class="btn btn-soft" data-close>Cancelar</button><button class="btn btn-blue" id="saveEditBtn">Guardar cambios</button></div></div></div>';}
function menuHtml(){const d=state.current;if(!d)return '';return '<div class="sheet-bg" id="sheetBg"><div class="bottom-sheet"><div class="sheet-handle"></div><div class="sheet-title"><h3>'+esc(d.name)+'</h3><p>Selecciona una opción</p></div><button class="sheet-option" data-action="edit"><span class="sheet-icon">✎</span><span><strong>Editar</strong><span>Cambiar nombre o enlace del documento</span></span></button><button class="sheet-option" data-action="general"><span class="sheet-icon">∑</span><span><strong>Estadísticas generales</strong><span>Totales y promedio por moneda</span></span></button><button class="sheet-option" data-action="individual"><span class="sheet-icon">≡</span><span><strong>Estadísticas individuales</strong><span>Totales y promedios por trabajador</span></span></button><button class="sheet-option" data-action="query"><span class="sheet-icon">⌕</span><span><strong>Consulta</strong><span>Filtrar por hoja, fecha y moneda</span></span></button><button class="sheet-option danger" data-action="delete"><span class="sheet-icon">⌫</span><span><strong>Eliminar</strong><span>Quitar este documento del dispositivo</span></span></button></div></div>';}
function deleteConfirmHtml(){const d=state.current;if(!d)return '';return '<div class="modal-bg" id="deleteConfirmBg"><div class="modal-card delete-confirm-card"><div class="delete-confirm-icon">⌫</div><h2>Eliminar documento</h2><p>¿Seguro que quieres eliminar <strong>'+esc(d.name)+'</strong> de este dispositivo?</p><div class="modal-actions"><button class="btn btn-soft" data-close>Cancelar</button><button class="btn btn-danger" id="confirmDeleteBtn">Eliminar</button></div></div></div>';}
function overlayHtml(){if(state.view==='add')return addModalHtml();if(state.view==='menu')return menuHtml();if(state.view==='edit')return editModalHtml();if(state.view==='delete-confirm')return deleteConfirmHtml();return '';}
function pageHeader(subtitle){const d=state.current;return '<header class="detail-hero"><div class="detail-inner"><div class="back" id="backBtn">← Atrás</div><div class="detail-title"><div class="brand-mark brand-mark-logo">'+NEXUS_LOGO+'</div><div><h1>'+esc(d?.name||'')+'</h1><p>'+esc(subtitle)+'</p></div></div></div></header>';}
function generalStatsHtml(s){const days=s.daysInMonth||0;return '<div class="stats-card"><div class="stat-currency-grid">'+CURRENCIES.map(([code,label])=>{const total=s.totals[code]||0,avg=days?total/days:0;return '<div class="stat-currency"><h3>'+label+'</h3><div class="stat-main">'+money(total)+'</div><div class="stat-sub">Promedio diario: '+money(avg)+'</div></div>';}).join('')+'</div></div>';}
function individualStatsHtml(s){const days=s.daysInMonth||0,headers=CURRENCIES.map(([,label])=>'<th>'+label+'</th>').join(''),rows=(s.sheetNames||[]).map(name=>{const w=s.workers[name];if(!w)return '';const cells=CURRENCIES.map(([code])=>{const total=w.totals[code]||0,avg=days?total/days:0;return '<td><div class="ind-total">'+money(total)+'</div><div class="ind-avg">Prom. diario '+money(avg)+'</div></td>';}).join('');return '<tr><td class="worker-name">'+esc(name)+'</td>'+cells+'</tr>';}).join('');return '<div class="stats-card"><div class="table-wrap"><table><thead><tr><th>Hoja</th>'+headers+'</tr></thead><tbody>'+rows+'</tbody></table></div></div>';}
function statsPageHtml(type){const d=state.current,s=state.summary[d?.id];let body;if(state.loading[d?.id]||!s)body='<div class="stats-card"><div class="loading-block">Calculando estadísticas…</div></div>';else if(s.error)body='<div class="stats-card"><div class="loading-block status-error">No se pudieron leer las hojas del documento.</div></div>';else body=type==='general'?generalStatsHtml(s):individualStatsHtml(s);return '<div class="app-shell">'+pageHeader(type==='general'?'Estadísticas generales':'Estadísticas por trabajador')+'<main class="main">'+body+'</main></div>';}
function queryPageHtml(){const d=state.current;if(!d)return homeHtml();const f=defaultFilter(d.id),sheetNames=state.summary[d.id]?.sheetNames||[],options=sheetNames.length?sheetNames.map(s=>'<option '+(s===f.sheet?'selected':'')+'>'+esc(s)+'</option>').join(''):'<option value="">Sin hojas activas</option>';let result='';if(state.view==='result'&&state.rows){const r=state.rows,label=r.currency==='USA'?'USD':r.currency,trs=r.items.length?r.items.map(x=>'<tr><td>'+esc(x.date)+'</td><td>'+esc(x.currency==='USA'?'USD':x.currency)+'</td><td>'+money(x.amount)+'</td><td>'+esc(x.name)+'</td></tr>').join(''):'<tr><td colspan="4">Sin resultados.</td></tr>';result='<div class="result-bg" id="resultBg"><div class="result-card"><div class="result-head"><div><h2>Resultado del filtro</h2><div class="result-sub">'+esc(r.sheet)+' · '+esc(r.from)+' → '+esc(r.to)+'</div></div><button class="btn-icon" id="closeResult">×</button></div><div class="metrics"><div class="metric"><span>OPERACIONES</span><strong>'+r.count+'</strong></div><div class="metric"><span>TOTAL COLUMNA C</span><strong>'+money(r.total)+'</strong></div><div class="metric"><span>MONEDA</span><strong>'+esc(label)+'</strong></div></div><div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Moneda</th><th>Monto (C)</th><th>Nombre</th></tr></thead><tbody>'+trs+'</tbody></table></div></div></div>';}return '<div class="app-shell">'+pageHeader('Consulta detallada del documento')+'<main class="main"><div class="filters-card"><div class="filters"><div class="field wide"><label>Hoja</label><select id="sheet" '+(sheetNames.length?'':'disabled')+'>'+options+'</select></div><div class="field"><label>Fecha inicial</label><input id="from" type="date" value="'+esc(f.from)+'"></div><div class="field"><label>Fecha final</label><input id="to" type="date" value="'+esc(f.to)+'"></div><div class="field"><label>Moneda</label><select id="currency">'+CURRENCIES.map(([code,label])=>'<option value="'+code+'" '+(code===f.currency?'selected':'')+'>'+label+'</option>').join('')+'</select></div><button class="btn btn-blue filter-action" id="filterBtn" '+(sheetNames.length?'':'disabled')+'>Filtrar</button></div></div></main>'+result+'</div>';}
function showPublicAccessWarning(){document.getElementById('publicAccessWarning')?.remove();const bg=document.createElement('div');bg.className='modal-bg';bg.id='publicAccessWarning';bg.innerHTML='<div class="modal-card access-warning-card"><div class="access-warning-icon">!</div><h2>No se puede leer el documento</h2><p>Para agregar este Google Sheet, activa el acceso <strong>Cualquier persona con el vínculo</strong> con permiso de <strong>Lector</strong>.</p><p class="access-warning-steps">Google Sheets → Compartir → Acceso general → Cualquier persona con el vínculo → Lector.</p><div class="modal-actions"><button class="btn btn-blue" id="closePublicAccessWarning">Entendido</button></div></div>';document.body.appendChild(bg);}
function render(){const app=document.getElementById('app');if(!app)return;if(['home','add','menu','edit','delete-confirm'].includes(state.view))app.innerHTML=homeHtml()+overlayHtml();else if(state.view==='general'||state.view==='individual')app.innerHTML=statsPageHtml(state.view);else app.innerHTML=queryPageHtml();}
function isBrowserReload(){try{const nav=performance.getEntriesByType?.('navigation')?.[0];if(nav?.type==='reload')return true;}catch(e){}try{if(performance.navigation?.type===1)return true;}catch(e){}return false;}
async function runReloadRefresh(){const unlocked=docs.filter(d=>!d.locked);if(!unlocked.length)return;reloadRefreshing=true;for(const doc of unlocked){delete state.summary[doc.id];state.loading[doc.id]=false;}render();try{for(const doc of unlocked)await loadSummary(doc);}finally{reloadRefreshing=false;render();}}

window.addEventListener('popstate',e=>applyHistory(e.state));
document.addEventListener('change',e=>{if(['sheet','from','to','currency'].includes(e.target.id))syncFilterInputs();if(e.target.id==='homeChartCurrency'){state.homeChartCurrency=e.target.value;render();}});
document.addEventListener('keydown',e=>{if(e.target.id==='refreshAllBtn'&&(e.key==='Enter'||e.key===' ')){e.preventDefault();refreshAllDocuments();}});
function openAddFast(e){const target=e.target.closest?.('#addBtn,#emptyAddBtn');if(!target||state.view==='add')return;e.preventDefault();e.stopImmediatePropagation();route('add',null,true);}
document.addEventListener('pointerdown',openAddFast,true);
document.addEventListener('touchstart',openAddFast,{capture:true,passive:false});
document.addEventListener('click',async e=>{const t=e.target;if(t.id==='closePublicAccessWarning'||t.id==='publicAccessWarning'){document.getElementById('publicAccessWarning')?.remove();return;}const lock=t.closest?.('[data-doc-lock]');if(lock){e.preventDefault();e.stopImmediatePropagation();const doc=docs.find(d=>d.id===lock.dataset.docLock);if(doc){doc.locked=!doc.locked;saveDocs();render();}return;}if(t.id==='refreshAllBtn'||t.closest?.('#refreshAllBtn')){e.preventDefault();e.stopImmediatePropagation();await refreshAllDocuments();return;}if(t.closest?.('[data-close]')){history.back();return;}if((t.id==='modalBg'||t.id==='sheetBg'||t.id==='deleteConfirmBg')&&e.target===t){history.back();return;}if(t.id==='saveBtn'){e.preventDefault();e.stopImmediatePropagation();const name=String(document.getElementById('docName')?.value||'').trim(),url=String(document.getElementById('docUrl')?.value||'').trim();if(!name||!extractId(url)){alert('Escribe un nombre y un enlace válido de Google Sheets.');return;}const btn=document.getElementById('saveBtn');if(btn){btn.disabled=true;btn.textContent='Comprobando…';}if(!await spreadsheetIsPublic(url)){if(btn){btn.disabled=false;btn.textContent='Guardar';}showPublicAccessWarning();return;}const doc={id:'d'+Date.now(),name,url,locked:false};docs.push(doc);saveDocs();goHomeReplace();setTimeout(()=>loadSummary(doc,{force:true}),0);return;}if(t.id==='saveEditBtn'){e.preventDefault();e.stopImmediatePropagation();const name=String(document.getElementById('editName')?.value||'').trim(),url=String(document.getElementById('editUrl')?.value||'').trim();if(!name||!extractId(url)){alert('Escribe un nombre y un enlace válido de Google Sheets.');return;}const d=docs.find(x=>x.id===state.current?.id);if(d){d.name=name;d.url=url;saveDocs();}goHomeReplace();return;}if(t.id==='backBtn'){goHomeReplace();return;}if(t.id==='filterBtn'){doFilter();return;}if(t.id==='closeResult'){history.back();return;}if(t.id==='resultBg'&&e.target===t){history.back();return;}if(t.id==='confirmDeleteBtn'){const d=state.current;if(d){docs=docs.filter(x=>x.id!==d.id);delete state.summary[d.id];delete state.loading[d.id];delete state.filters[d.id];saveDocs();saveSummary();}goHomeReplace();return;}const action=t.closest?.('[data-action]');if(action){const a=action.dataset.action,d=state.current;if(!d)return;if(a==='delete'){route('delete-confirm',d.id,true);return;}if(['edit','general','individual','query'].includes(a)){route(a,d.id,true);return;}}const card=t.closest?.('[data-open]');if(card){route('menu',card.dataset.open,true);return;}});

loadLocalState();
history.replaceState({nexus:true,view:'home',docId:null},'',location.href);
saveDocs();
render();
if(isBrowserReload())runReloadRefresh();
