'use strict';

const STORAGE_KEY='nexus_consulta_docs_v2';
const PREFERRED_CURRENCIES=['USD','CUP','EUR','MXN','CAD','REAL','ZELLE'];
const NEXUS_LOGO='<img class="nexus-app-logo" src="./app-icon.svg?v=20260819b" alt="Nexus Consulta">';
let docs=[];let state={view:'home',current:null,loading:false,query:null,filters:{}};
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function uid(){return (crypto?.randomUUID?.()||('doc-'+Date.now()+'-'+Math.random().toString(36).slice(2)));}
function loadDocs(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');docs=Array.isArray(x)?x:[];}catch{docs=[];}}
function saveDocs(){localStorage.setItem(STORAGE_KEY,JSON.stringify(docs));}
function extractId(url){const m=String(url||'').match(/\/spreadsheets\/d\/([a-zA-Z0-9-_]+)/);return m?m[1]:'';}
function parseAmount(v){if(typeof v==='number')return Number.isFinite(v)?v:0;let s=String(v??'').trim().replace(/\s/g,'').replace(/[^0-9,.-]/g,'');if(!s)return 0;if(s.includes(',')&&s.includes('.'))s=s.lastIndexOf(',')>s.lastIndexOf('.')?s.replace(/\./g,'').replace(',','.'):s.replace(/,/g,'');else if(s.includes(',')){const p=s.split(',');s=(p.length===2&&p[1].length<=2)?p[0].replace(/\./g,'')+'.'+p[1]:s.replace(/,/g,'');}const n=Number(s);return Number.isFinite(n)?n:0;}
function parseDate(v){const s=String(v||'').trim();let m=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{2,4})$/);if(m){let y=+m[3];if(y<100)y+=2000;const d=new Date(y,+m[2]-1,+m[1]);return Number.isNaN(d.getTime())?null:d;}m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);if(m){const d=new Date(+m[1],+m[2]-1,+m[3]);return Number.isNaN(d.getTime())?null:d;}return null;}
function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(q){if(c==='"'&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')q=false;else cell+=c;}else if(c==='"')q=true;else if(c===','){row.push(cell);cell='';}else if(c==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell='';}else cell+=c;}if(cell.length||row.length){row.push(cell.replace(/\r$/,''));rows.push(row);}return rows;}
function normalizeCurrency(v){const c=String(v||'').trim().toUpperCase();if(!c)return '';const aliases={USA:'USD',US:'USD',DOLAR:'USD',DÓLAR:'USD',MXC:'MXN',MEX:'MXN',BRL:'REAL',REAIS:'REAL'};return aliases[c]||c;}
function fmt(n){return Number(n||0).toLocaleString('es-MX',{maximumFractionDigits:2});}function rounded(n){return Math.round((Number(n||0)+Number.EPSILON)*100)/100;}
function checkboxValueIsChecked(v){const s=String(v??'').trim().toUpperCase();return v===true||v===1||['TRUE','VERDADERO','1','SI','SÍ'].includes(s);}
function isHtml(text,type=''){return type.includes('text/html')||/<!doctype html|<html/i.test(text)||/sign in|iniciar sesi[oó]n|request access|solicitar acceso/i.test(text);}
async function timedFetch(url,options={},timeoutMs=30000){const controller=new AbortController();const timer=timeoutMs?setTimeout(()=>controller.abort(),timeoutMs):null;try{return await fetch(url,{...options,signal:controller.signal});}catch(e){if(e?.name==='AbortError')throw new Error('Google Sheets tardó demasiado en responder');throw e;}finally{if(timer)clearTimeout(timer);}}
async function mapLimit(items,limit,fn){const out=new Array(items.length);let cursor=0;async function worker(){while(true){const i=cursor++;if(i>=items.length)return;out[i]=await fn(items[i],i);}}await Promise.all(Array.from({length:Math.min(limit,Math.max(1,items.length))},worker));return out;}
async function spreadsheetIsPublic(url){const id=extractId(url);if(!id)return false;try{const u=`https://docs.google.com/spreadsheets/d/${encodeURIComponent(id)}/gviz/tq?tqx=out:json&headers=0&range=A1:A1&_=${Date.now()}`;const r=await timedFetch(u,{cache:'no-store'},20000);if(!r.ok)return false;const type=(r.headers.get('content-type')||'').toLowerCase(),text=await r.text();if(isHtml(text,type))return false;const a=text.indexOf('{'),b=text.lastIndexOf('}');if(a<0||b<=a)return false;const p=JSON.parse(text.slice(a,b+1));return !p.status||p.status==='ok';}catch{return false;}}
async function readSheetU1(doc,sheet){const id=extractId(doc.url),u=`https://docs.google.com/spreadsheets/d/${encodeURIComponent(id)}/gviz/tq?tqx=out:csv&headers=0&range=U1:U1&sheet=${encodeURIComponent(sheet)}&_=${Date.now()}`;const r=await timedFetch(u,{cache:'no-store'},30000);if(!r.ok)throw new Error('No se pudo comprobar U1');const type=(r.headers.get('content-type')||'').toLowerCase(),text=await r.text();if(isHtml(text,type))throw new Error('Sin acceso mediante vínculo');return checkboxValueIsChecked(parseCSV(text)?.[0]?.[0]);}
async function discoverActiveSheets(doc){const id=extractId(doc.url);if(!id)throw new Error('Enlace no válido');if(!window.XLSX)throw new Error('No se pudo cargar el lector de hojas');const cacheKey='nexus_consulta_sheets_'+id;let names=[];try{const cached=JSON.parse(sessionStorage.getItem(cacheKey)||'null');if(cached&&Array.isArray(cached.names)&&Date.now()-cached.time<3600000)names=cached.names;}catch{}if(!names.length){const u=`https://docs.google.com/spreadsheets/d/${encodeURIComponent(id)}/export?format=xlsx&_=${Date.now()}`;const r=await timedFetch(u,{cache:'no-store'},120000);if(!r.ok)throw new Error('No se pudo leer la estructura del documento');const type=(r.headers.get('content-type')||'').toLowerCase();if(type.includes('text/html'))throw new Error('El documento no tiene acceso mediante vínculo');let wb;try{wb=XLSX.read(await r.arrayBuffer(),{bookSheets:true,bookProps:false});}catch{throw new Error('No se pudo leer la lista de hojas');}names=Array.isArray(wb.SheetNames)?wb.SheetNames:[];try{sessionStorage.setItem(cacheKey,JSON.stringify({time:Date.now(),names}));}catch{}}const checks=await mapLimit(names,10,async name=>{try{return {name,enabled:await readSheetU1(doc,name)};}catch(e){return {name,enabled:false,error:e};}});if(names.length&&checks.every(x=>x.error))throw checks[0].error;return checks.filter(x=>x.enabled).map(x=>x.name);}
async function fetchSheetRows(doc,sheet){const id=extractId(doc.url),u=`https://docs.google.com/spreadsheets/d/${encodeURIComponent(id)}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(sheet)}&range=A:C&_=${Date.now()}`;const r=await timedFetch(u,{cache:'no-store'},60000);if(!r.ok)throw new Error(`Google respondió ${r.status}`);const type=(r.headers.get('content-type')||'').toLowerCase(),text=await r.text();if(isHtml(text,type))throw new Error('Sin acceso mediante vínculo');return parseCSV(text);}
function defaultFilter(docId){if(!state.filters[docId]){const now=new Date(),y=now.getFullYear(),m=String(now.getMonth()+1).padStart(2,'0'),last=String(new Date(y,now.getMonth()+1,0).getDate()).padStart(2,'0');state.filters[docId]={from:`${y}-${m}-01`,to:`${y}-${m}-${last}`};}return state.filters[docId];}
function syncFilterInputs(){const d=state.current;if(!d)return null;const f=defaultFilter(d.id),a=document.getElementById('from'),b=document.getElementById('to');if(a)f.from=a.value;if(b)f.to=b.value;return f;}
async function runQuery(){const d=state.current,f=syncFilterInputs();if(!d||!f)return;if(!f.from||!f.to)return alert('Selecciona las dos fechas.');const start=new Date(f.from+'T00:00:00'),end=new Date(f.to+'T23:59:59');if(start>end)return alert('La fecha inicial no puede ser posterior a la fecha final.');state.loading=true;state.query=null;render();try{const sheets=await discoverActiveSheets(d);if(!sheets.length)throw new Error('No hay hojas activadas para consulta.');const results=await mapLimit(sheets,6,async sheet=>{try{const rows=await fetchSheetRows(d,sheet);let inherited=null,operations=0;const totals={};for(const row of rows){const detected=parseDate(row[0]);if(detected)inherited=detected;if(!inherited||inherited<start||inherited>end)continue;const currency=normalizeCurrency(row[1]);if(!currency)continue;const raw=row[2];if(raw==null||String(raw).trim()==='')continue;totals[currency]=(totals[currency]||0)+parseAmount(raw);operations++;}Object.keys(totals).forEach(k=>totals[k]=rounded(totals[k]));return {sheet,totals,operations};}catch(e){return {sheet,totals:{},operations:0,error:e?.message||String(e)};}});const currencySet=new Set(),grand={};let operations=0;for(const r of results){operations+=r.operations||0;for(const [c,v] of Object.entries(r.totals||{})){currencySet.add(c);grand[c]=(grand[c]||0)+v;}}Object.keys(grand).forEach(k=>grand[k]=rounded(grand[k]));const currencies=[...PREFERRED_CURRENCIES.filter(c=>currencySet.has(c)),...[...currencySet].filter(c=>!PREFERRED_CURRENCIES.includes(c)).sort()];state.query={from:f.from,to:f.to,rows:results,currencies,totals:grand,operations,sheets:sheets.length};}catch(e){alert('No se pudo consultar el Spreadsheet. '+(e?.message||e));}finally{state.loading=false;render();}}
function goHome(){state.view='home';state.current=null;state.query=null;render();}function openDoc(id){const d=docs.find(x=>x.id===id);if(!d)return;state.current=d;state.view='menu';state.query=null;render();}function openQuery(){if(!state.current)return;state.view='query';state.query=null;render();}
function homeHtml(){const cards=docs.length?`<div class="docs-grid">${docs.map(d=>`<article class="doc-card" data-open="${esc(d.id)}"><div class="doc-top"><div class="doc-title-wrap"><h3 class="doc-title">${esc(d.name)}</h3><div class="doc-kicker"><span class="dot"></span><span>Consulta de operaciones</span></div></div></div><div class="query-card-home"><div class="query-home-icon">⌕</div><div><strong>Consultar documento</strong><span>Filtra todas las hojas y todas las monedas por fecha.</span></div></div><div class="card-foot"><span>Listo para consultar</span><span>•••</span></div></article>`).join('')}</div>`:`<div class="empty"><div class="empty-icon">⌕</div><h2>Aún no hay documentos</h2><p>Agrega un Google Spreadsheet para consultar todas sus hojas y monedas desde una sola tabla.</p><button class="btn btn-add" id="emptyAddBtn"><span class="add-icon">+</span><span class="add-label">Agregar documento</span></button></div>`;return `<div class="app-shell"><header class="hero"><div class="hero-inner"><div class="brand"><div class="brand-mark brand-mark-logo">${NEXUS_LOGO}</div><div class="brand-copy"><h1>Nexus Consulta</h1><p>Consulta consolidada de operaciones</p></div></div><button class="btn btn-add" id="addBtn"><span class="add-icon">+</span><span class="add-label">Agregar documento</span></button></div></header><main class="main"><div class="section-head"><h2 class="section-title">Documentos</h2></div>${cards}</main></div>`;}
function addHtml(){return `<div class="modal-bg"><div class="modal-card"><div class="modal-head"><h2>Agregar documento</h2><button class="btn-icon" data-close>×</button></div><div class="field"><label>Nombre</label><input id="docName" placeholder="Nombre"></div><div class="field"><label>Enlace de Google Sheets</label><input id="docUrl" placeholder="Pega aquí el enlace"></div><div class="modal-actions"><button class="btn btn-soft" data-close>Cancelar</button><button class="btn btn-blue" id="saveBtn">Guardar</button></div></div></div>`;}
function editHtml(){const d=state.current;return `<div class="modal-bg"><div class="modal-card"><div class="modal-head"><h2>Editar documento</h2><button class="btn-icon" data-close>×</button></div><div class="field"><label>Nombre</label><input id="editName" value="${esc(d.name)}"></div><div class="field"><label>Enlace de Google Sheets</label><input id="editUrl" value="${esc(d.url)}"></div><div class="modal-actions"><button class="btn btn-soft" data-close>Cancelar</button><button class="btn btn-blue" id="saveEditBtn">Guardar cambios</button></div></div></div>`;}
function menuHtml(){const d=state.current;return `<div class="sheet-bg"><div class="bottom-sheet"><div class="sheet-handle"></div><div class="sheet-title"><h3>${esc(d.name)}</h3><p>Selecciona una opción</p></div><button class="sheet-option" data-action="query"><span class="sheet-icon">⌕</span><span><strong>Consulta</strong><span>Todas las hojas y monedas por fecha</span></span></button><button class="sheet-option" data-action="edit"><span class="sheet-icon">✎</span><span><strong>Editar</strong><span>Cambiar nombre o enlace</span></span></button><button class="sheet-option danger" data-action="delete"><span class="sheet-icon">⌫</span><span><strong>Eliminar</strong><span>Quitar este documento</span></span></button></div></div>`;}
function deleteHtml(){const d=state.current;return `<div class="modal-bg"><div class="modal-card delete-confirm-card"><div class="delete-confirm-icon">⌫</div><h2>Eliminar documento</h2><p>Se quitará “${esc(d.name)}” de este dispositivo.</p><div class="modal-actions"><button class="btn btn-soft" data-close>Cancelar</button><button class="btn btn-danger" id="confirmDelete">Eliminar</button></div></div></div>`;}
function queryHtml(){const d=state.current,f=defaultFilter(d.id),q=state.query;let result='';if(state.loading)result='<div class="loading-block">Validando hojas activas y procesando únicamente esas hojas…</div>';else if(q){const cols=q.currencies.length?q.currencies:['—'],head=cols.map(c=>`<th>${esc(c)}</th>`).join(''),body=q.rows.map(r=>`<tr><td class="worker-name">${esc(r.sheet)}${r.error?`<div class="status-error">${esc(r.error)}</div>`:''}</td>${cols.map(c=>`<td>${c==='—'?'—':fmt(r.totals?.[c]||0)}</td>`).join('')}<td>${r.operations||0}</td></tr>`).join(''),total=cols.map(c=>`<td>${c==='—'?'—':fmt(q.totals?.[c]||0)}</td>`).join('');result=`<div class="query-summary"><div><span>PERÍODO</span><strong>${esc(q.from)} → ${esc(q.to)}</strong></div><div><span>OPERACIONES</span><strong>${q.operations}</strong></div></div><div class="table-wrap"><table><thead><tr><th>Hoja</th>${head}<th>Operaciones</th></tr></thead><tbody>${body}<tr class="query-total-row"><td>TOTAL</td>${total}<td>${q.operations}</td></tr></tbody></table></div>`;}return `<div class="app-shell"><header class="detail-hero"><div class="detail-inner"><div class="back" id="backHome">← Volver</div><div class="detail-title"><div><h1>${esc(d.name)}</h1><p>Consulta consolidada</p></div></div></div></header><main class="main"><section class="filters-card query-only-card"><div class="query-date-grid"><div class="field"><label>Fecha inicial</label><input type="date" id="from" value="${esc(f.from)}"></div><div class="field"><label>Fecha final</label><input type="date" id="to" value="${esc(f.to)}"></div><button class="btn btn-blue filter-action" id="queryBtn" ${state.loading?'disabled':''}>${state.loading?'Procesando…':'Consultar'}</button></div>${result}</section></main></div>`;}
function render(){const app=document.getElementById('app');if(state.view==='home')app.innerHTML=homeHtml();else if(state.view==='add')app.innerHTML=homeHtml()+addHtml();else if(state.view==='menu')app.innerHTML=homeHtml()+menuHtml();else if(state.view==='edit')app.innerHTML=homeHtml()+editHtml();else if(state.view==='delete')app.innerHTML=homeHtml()+deleteHtml();else if(state.view==='query')app.innerHTML=queryHtml();bind();}
function bind(){document.querySelectorAll('[data-open]').forEach(el=>el.onclick=()=>openDoc(el.dataset.open));const add=()=>{state.view='add';render();};document.getElementById('addBtn')?.addEventListener('click',add);document.getElementById('emptyAddBtn')?.addEventListener('click',add);document.querySelectorAll('[data-close]').forEach(el=>el.onclick=()=>{state.view=state.current?'menu':'home';render();});document.querySelector('[data-action="query"]')?.addEventListener('click',openQuery);document.querySelector('[data-action="edit"]')?.addEventListener('click',()=>{state.view='edit';render();});document.querySelector('[data-action="delete"]')?.addEventListener('click',()=>{state.view='delete';render();});document.getElementById('backHome')?.addEventListener('click',goHome);document.getElementById('queryBtn')?.addEventListener('click',runQuery);document.getElementById('saveBtn')?.addEventListener('click',async()=>{const name=document.getElementById('docName').value.trim(),url=document.getElementById('docUrl').value.trim();if(!name||!extractId(url))return alert('Escribe un nombre y un enlace válido de Google Sheets.');const btn=document.getElementById('saveBtn');btn.disabled=true;btn.textContent='Comprobando…';if(!await spreadsheetIsPublic(url)){btn.disabled=false;btn.textContent='Guardar';return alert('No puedo leer el documento. Activa “Cualquier persona con el enlace → Lector”.');}docs.push({id:uid(),name:name.charAt(0).toUpperCase()+name.slice(1),url});saveDocs();state.view='home';render();});document.getElementById('saveEditBtn')?.addEventListener('click',async()=>{const name=document.getElementById('editName').value.trim(),url=document.getElementById('editUrl').value.trim();if(!name||!extractId(url))return alert('Datos no válidos.');if(url!==state.current.url&&!await spreadsheetIsPublic(url))return alert('No puedo leer ese documento.');Object.assign(state.current,{name:name.charAt(0).toUpperCase()+name.slice(1),url});saveDocs();state.view='home';state.current=null;render();});document.getElementById('confirmDelete')?.addEventListener('click',()=>{docs=docs.filter(x=>x.id!==state.current.id);saveDocs();state.current=null;state.view='home';render();});}
loadDocs();render();