'use strict';
const STORAGE_KEY='nexus_consulta_docs_v2',PREFERRED_CURRENCIES=['USD','CUP','EUR','MXN','CAD','REAL','ZELLE'],XLSX_URL='https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js',NEXUS_LOGO='<img class="nexus-app-logo" src="./app-icon.svg?v=20260819e" alt="Nexus Consulta">';
let docs=[],xlsxPromise=null,state={view:'home',current:null,loading:false,query:null,filters:{}};
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c])),fmt=n=>Number(n||0).toLocaleString('es-MX',{maximumFractionDigits:2}),rounded=n=>Math.round((Number(n||0)+Number.EPSILON)*100)/100;
function uid(){return crypto?.randomUUID?.()||`doc-${Date.now()}-${Math.random().toString(36).slice(2)}`}
function loadDocs(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');docs=Array.isArray(x)?x:[]}catch{docs=[]}}
function saveDocs(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(docs))}catch{}}
function extractId(url){return String(url||'').match(/\/spreadsheets\/d\/([\w-]+)/)?.[1]||''}
function parseAmount(v){if(typeof v==='number')return Number.isFinite(v)?v:0;let s=String(v??'').trim().replace(/\s/g,'').replace(/[^0-9,.-]/g,'');if(!s)return 0;if(s.includes(',')&&s.includes('.'))s=s.lastIndexOf(',')>s.lastIndexOf('.')?s.replace(/\./g,'').replace(',','.'):s.replace(/,/g,'');else if(s.includes(',')){const p=s.split(',');s=p.length===2&&p[1].length<=2?p[0].replace(/\./g,'')+'.'+p[1]:s.replace(/,/g,'')}const n=Number(s);return Number.isFinite(n)?n:0}
function parseDateKey(v){const s=String(v||'').trim();let m=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{2,4})$/);if(m){let y=+m[3];if(y<100)y+=2000;const mo=+m[2],d=+m[1];return mo>0&&mo<13&&d>0&&d<32?y*10000+mo*100+d:0}m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);if(!m)return 0;const y=+m[1],mo=+m[2],d=+m[3];return mo>0&&mo<13&&d>0&&d<32?y*10000+mo*100+d:0}
function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(q){if(c==='"'&&text[i+1]==='"'){cell+='"';i++}else if(c==='"')q=false;else cell+=c}else if(c==='"')q=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell.replace(/\r$/,''));rows.push(row)}return rows}
function normalizeCurrency(v){const c=String(v||'').trim().toUpperCase();return ({USA:'USD',US:'USD',DOLAR:'USD',DÓLAR:'USD',MXC:'MXN',MEX:'MXN',BRL:'REAL',REAIS:'REAL'})[c]||c}
function checkboxValueIsChecked(v){const s=String(v??'').trim().toUpperCase();return v===true||v===1||['TRUE','VERDADERO','1','SI','SÍ'].includes(s)}
function isHtml(text,type=''){return type.includes('text/html')||/<!doctype html|<html|sign in|iniciar sesi[oó]n|request access|solicitar acceso/i.test(text)}
async function timedFetch(url,timeout=30000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{return await fetch(url,{cache:'no-store',signal:c.signal})}catch(e){if(e?.name==='AbortError')throw new Error('Google Sheets tardó demasiado en responder');throw e}finally{clearTimeout(t)}}
async function mapLimit(items,limit,fn){const out=new Array(items.length);let i=0;async function worker(){while(i<items.length){const n=i++;out[n]=await fn(items[n],n)}}await Promise.all(Array.from({length:Math.min(limit,Math.max(1,items.length))},worker));return out}
function ensureXlsx(){if(window.XLSX)return Promise.resolve(window.XLSX);if(xlsxPromise)return xlsxPromise;xlsxPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=XLSX_URL;s.async=true;s.onload=()=>window.XLSX?resolve(window.XLSX):reject(new Error('No se pudo cargar el lector de hojas'));s.onerror=()=>reject(new Error('No se pudo cargar el lector de hojas'));document.head.appendChild(s)});return xlsxPromise}
async function spreadsheetIsPublic(url){const id=extractId(url);if(!id)return false;try{const r=await timedFetch(`https://docs.google.com/spreadsheets/d/${encodeURIComponent(id)}/gviz/tq?tqx=out:json&headers=0&range=A1:A1&_=${Date.now()}`,20000);if(!r.ok)return false;const type=(r.headers.get('content-type')||'').toLowerCase(),text=await r.text();if(isHtml(text,type))return false;const a=text.indexOf('{'),b=text.lastIndexOf('}');if(a<0||b<=a)return false;const p=JSON.parse(text.slice(a,b+1));return !p.status||p.status==='ok'}catch{return false}}
async function readSheetU1(doc,sheet){const id=extractId(doc.url),r=await timedFetch(`https://docs.google.com/spreadsheets/d/${encodeURIComponent(id)}/gviz/tq?tqx=out:csv&headers=0&range=U1:U1&sheet=${encodeURIComponent(sheet)}&_=${Date.now()}`,30000);if(!r.ok)throw new Error('No se pudo comprobar U1');const type=(r.headers.get('content-type')||'').toLowerCase(),text=await r.text();if(isHtml(text,type))throw new Error('Sin acceso mediante vínculo');return checkboxValueIsChecked(parseCSV(text)?.[0]?.[0])}
async function discoverActiveSheets(doc){const id=extractId(doc.url);if(!id)throw new Error('Enlace no válido');const key=`nexus_consulta_sheetnames_${id}`;let names=[];try{const c=JSON.parse(localStorage.getItem(key)||'null');if(c&&Array.isArray(c.names)&&Date.now()-c.time<3600000)names=c.names}catch{}if(!names.length){const XLSX=await ensureXlsx(),r=await timedFetch(`https://docs.google.com/spreadsheets/d/${encodeURIComponent(id)}/export?format=xlsx&_=${Date.now()}`,120000);if(!r.ok)throw new Error('No se pudo leer la estructura del documento');if((r.headers.get('content-type')||'').toLowerCase().includes('text/html'))throw new Error('El documento no tiene acceso mediante vínculo');let wb;try{wb=XLSX.read(await r.arrayBuffer(),{bookSheets:true,bookProps:false})}catch{throw new Error('No se pudo leer la lista de hojas')}names=Array.isArray(wb.SheetNames)?wb.SheetNames:[];try{localStorage.setItem(key,JSON.stringify({time:Date.now(),names}))}catch{}}const checks=await mapLimit(names,10,async name=>{try{return {name,enabled:await readSheetU1(doc,name)}}catch(e){return {name,error:e}}});if(names.length&&checks.every(x=>x.error))throw checks[0].error;return checks.filter(x=>x.enabled).map(x=>x.name)}
async function fetchSheetRows(doc,sheet){const id=extractId(doc.url),r=await timedFetch(`https://docs.google.com/spreadsheets/d/${encodeURIComponent(id)}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(sheet)}&range=A:C&_=${Date.now()}`,60000);if(!r.ok)throw new Error(`Google respondió ${r.status}`);const type=(r.headers.get('content-type')||'').toLowerCase(),text=await r.text();if(isHtml(text,type))throw new Error('Sin acceso mediante vínculo');return parseCSV(text)}
function defaultFilter(id){if(!state.filters[id]){const n=new Date(),y=n.getFullYear(),m=String(n.getMonth()+1).padStart(2,'0'),last=String(new Date(y,n.getMonth()+1,0).getDate()).padStart(2,'0');state.filters[id]={from:`${y}-${m}-01`,to:`${y}-${m}-${last}`}}return state.filters[id]}
function syncFilterInputs(){const d=state.current;if(!d)return null;const f=defaultFilter(d.id),a=$('from'),b=$('to');if(a)f.from=a.value;if(b)f.to=b.value;return f}
async function runQuery(){const d=state.current,f=syncFilterInputs();if(!d||!f)return;if(!f.from||!f.to)return alert('Selecciona las dos fechas.');const start=parseDateKey(f.from),end=parseDateKey(f.to);if(start>end)return alert('La fecha inicial no puede ser posterior a la fecha final.');state.loading=true;state.query=null;render();try{const sheets=await discoverActiveSheets(d);if(!sheets.length)throw new Error('No hay hojas activadas para consulta.');const results=await mapLimit(sheets,6,async sheet=>{try{const rows=await fetchSheetRows(d,sheet),totals={};let inherited=0;for(const row of rows){const date=parseDateKey(row[0]);if(date)inherited=date;if(!inherited||inherited<start||inherited>end)continue;const currency=normalizeCurrency(row[1]),raw=row[2];if(!currency||raw==null||String(raw).trim()==='')continue;totals[currency]=(totals[currency]||0)+parseAmount(raw)}for(const k in totals)totals[k]=rounded(totals[k]);return {sheet,totals}}catch(e){return {sheet,totals:{},error:e?.message||String(e)}}});const set=new Set(),grand={};for(const r of results)for(const [c,v] of Object.entries(r.totals)){set.add(c);grand[c]=(grand[c]||0)+v}for(const k in grand)grand[k]=rounded(grand[k]);const currencies=[...PREFERRED_CURRENCIES.filter(c=>set.has(c)),...[...set].filter(c=>!PREFERRED_CURRENCIES.includes(c)).sort()];state.query={rows:results,currencies,totals:grand}}catch(e){alert('No se pudo consultar el Spreadsheet. '+(e?.message||e))}finally{state.loading=false;render()}}
function goHome(){state.view='home';state.current=null;state.query=null;render()}
function openDoc(id){const d=docs.find(x=>x.id===id);if(!d)return;state.current=d;state.view='query';state.query=null;render()}
function openMenu(id){const d=docs.find(x=>x.id===id);if(!d)return;state.current=d;state.view='menu';state.query=null;history.pushState({nexusConsultaOverlay:'menu'},'',location.href);render()}
function closeMenu(fromHistory=false){if(state.view!=='menu')return;if(!fromHistory&&history.state?.nexusConsultaOverlay==='menu'){history.back();return}state.view='home';state.current=null;state.query=null;render()}
function homeHtml(){const cards=docs.length?`<div class="docs-grid">${docs.map(d=>`<article class="doc-card" data-open="${esc(d.id)}"><div class="doc-top"><div class="doc-title-wrap"><h3 class="doc-title">${esc(d.name)}</h3><div class="doc-kicker"><span class="dot"></span><span>Consulta de operaciones</span></div></div></div><div class="query-card-home"><div class="query-home-icon">⌕</div><div><strong>Consultar documento</strong><span>Filtra todas las hojas y todas las monedas por fecha.</span></div></div><div class="card-foot"><span>Listo para consultar</span><button class="dots" data-menu="${esc(d.id)}" aria-label="Opciones del documento">•••</button></div></article>`).join('')}</div>`:`<div class="empty"><div class="empty-icon">⌕</div><h2>Aún no hay documentos</h2><p>Agrega un Google Spreadsheet para consultar todas sus hojas y monedas desde una sola tabla.</p><button class="btn btn-add" id="emptyAddBtn"><span class="add-icon">+</span><span class="add-label">Agregar documento</span></button></div>`;return `<div class="app-shell"><header class="hero"><div class="hero-inner"><div class="brand"><div class="brand-mark brand-mark-logo">${NEXUS_LOGO}</div><div class="brand-copy"><h1>Nexus Consulta</h1><p>Consulta consolidada de operaciones</p></div></div><button class="btn btn-add" id="addBtn"><span class="add-icon">+</span><span class="add-label">Agregar documento</span></button></div></header><main class="main"><div class="section-head"><h2 class="section-title">Documentos</h2></div>${cards}</main></div>`}
function addHtml(){return `<div class="modal-bg"><div class="modal-card"><div class="modal-head"><h2>Agregar documento</h2><button class="btn-icon" data-close>×</button></div><div class="field"><label>Nombre</label><input id="docName" placeholder="Nombre"></div><div class="field"><label>Enlace de Google Sheets</label><input id="docUrl" placeholder="Pega aquí el enlace"></div><div class="modal-actions"><button class="btn btn-soft" data-close>Cancelar</button><button class="btn btn-blue" id="saveBtn">Guardar</button></div></div></div>`}
function editHtml(){const d=state.current;return `<div class="modal-bg"><div class="modal-card"><div class="modal-head"><h2>Editar documento</h2><button class="btn-icon" data-close>×</button></div><div class="field"><label>Nombre</label><input id="editName" value="${esc(d.name)}"></div><div class="field"><label>Enlace de Google Sheets</label><input id="editUrl" value="${esc(d.url)}"></div><div class="modal-actions"><button class="btn btn-soft" data-close>Cancelar</button><button class="btn btn-blue" id="saveEditBtn">Guardar cambios</button></div></div></div>`}
function menuHtml(){const d=state.current;return `<div class="sheet-bg" id="docMenuBackdrop"><div class="bottom-sheet"><div class="sheet-handle"></div><div class="sheet-title"><h3>${esc(d.name)}</h3><p>Selecciona una opción</p></div><button class="sheet-option" data-action="edit"><span class="sheet-icon">✎</span><span><strong>Editar</strong><span>Cambiar nombre o enlace</span></span></button><button class="sheet-option danger" data-action="delete"><span class="sheet-icon">⌫</span><span><strong>Eliminar</strong><span>Quitar este documento</span></span></button></div></div>`}
function deleteHtml(){const d=state.current;return `<div class="modal-bg"><div class="modal-card delete-confirm-card"><div class="delete-confirm-icon">⌫</div><h2>Eliminar documento</h2><p>Se quitará “${esc(d.name)}” de este dispositivo.</p><div class="modal-actions"><button class="btn btn-soft" data-close>Cancelar</button><button class="btn btn-danger" id="confirmDelete">Eliminar</button></div></div></div>`}
function queryHtml(){const d=state.current,f=defaultFilter(d.id),q=state.query;let result='';if(state.loading)result='<div class="loading-block">Validando hojas activas y procesando únicamente esas hojas…</div>';else if(q){const cols=q.currencies.length?q.currencies:['—'],head=cols.map(c=>`<th>${esc(c)}</th>`).join(''),body=q.rows.map(r=>`<tr><td class="worker-name">${esc(r.sheet)}${r.error?`<div class="status-error">${esc(r.error)}</div>`:''}</td>${cols.map(c=>`<td>${c==='—'?'—':fmt(r.totals?.[c]||0)}</td>`).join('')}</tr>`).join(''),total=cols.map(c=>`<td>${c==='—'?'—':fmt(q.totals?.[c]||0)}</td>`).join('');result=`<div class="table-wrap"><table><thead><tr><th>Hoja</th>${head}</tr></thead><tbody>${body}<tr class="query-total-row"><td>TOTAL</td>${total}</tr></tbody></table></div>`}return `<div class="app-shell"><header class="detail-hero"><div class="detail-inner"><div class="back" id="backHome">← Volver</div><div class="detail-title"><div><h1>${esc(d.name)}</h1><p>Consulta consolidada</p></div></div></div></header><main class="main"><section class="filters-card query-only-card"><div class="query-date-grid"><div class="field"><label>Fecha inicial</label><input type="date" id="from" value="${esc(f.from)}"></div><div class="field"><label>Fecha final</label><input type="date" id="to" value="${esc(f.to)}"></div><button class="btn btn-blue filter-action" id="queryBtn" ${state.loading?'disabled':''}>${state.loading?'Procesando…':'Consultar'}</button></div>${result}</section></main></div>`}
function render(){const app=$('app');if(state.view==='home')app.innerHTML=homeHtml();else if(state.view==='add')app.innerHTML=homeHtml()+addHtml();else if(state.view==='menu')app.innerHTML=homeHtml()+menuHtml();else if(state.view==='edit')app.innerHTML=homeHtml()+editHtml();else if(state.view==='delete')app.innerHTML=homeHtml()+deleteHtml();else app.innerHTML=queryHtml();bind()}
function bind(){document.querySelectorAll('[data-open]').forEach(el=>el.onclick=()=>openDoc(el.dataset.open));document.querySelectorAll('[data-menu]').forEach(el=>el.onclick=e=>{e.preventDefault();e.stopPropagation();openMenu(el.dataset.menu)});const add=()=>{state.view='add';render()};$('addBtn')?.addEventListener('click',add);$('emptyAddBtn')?.addEventListener('click',add);document.querySelectorAll('[data-close]').forEach(el=>el.onclick=()=>{state.view=state.current?'menu':'home';render()});document.querySelector('[data-action="edit"]')?.addEventListener('click',()=>{state.view='edit';render()});document.querySelector('[data-action="delete"]')?.addEventListener('click',()=>{state.view='delete';render()});$('backHome')?.addEventListener('click',goHome);$('queryBtn')?.addEventListener('click',runQuery);$('docMenuBackdrop')?.addEventListener('click',e=>{if(e.target.id==='docMenuBackdrop')closeMenu(false)});$('saveBtn')?.addEventListener('click',async()=>{const name=$('docName').value.trim(),url=$('docUrl').value.trim();if(!name||!extractId(url))return alert('Escribe un nombre y un enlace válido de Google Sheets.');const b=$('saveBtn');b.disabled=true;b.textContent='Comprobando…';if(!await spreadsheetIsPublic(url)){b.disabled=false;b.textContent='Guardar';return alert('No puedo leer el documento. Activa “Cualquier persona con el enlace → Lector”.')}docs.push({id:uid(),name:name.charAt(0).toUpperCase()+name.slice(1),url});saveDocs();state.view='home';render()});$('saveEditBtn')?.addEventListener('click',async()=>{const name=$('editName').value.trim(),url=$('editUrl').value.trim();if(!name||!extractId(url))return alert('Datos no válidos.');if(url!==state.current.url&&!await spreadsheetIsPublic(url))return alert('No puedo leer ese documento.');Object.assign(state.current,{name:name.charAt(0).toUpperCase()+name.slice(1),url});saveDocs();state.view='home';state.current=null;render()});$('confirmDelete')?.addEventListener('click',()=>{docs=docs.filter(x=>x.id!==state.current.id);saveDocs();state.current=null;state.view='home';render()})}
window.addEventListener('popstate',()=>{if(state.view==='menu')closeMenu(true)});
loadDocs();render();