'use strict';

const STORAGE_KEY='nexus_consulta_docs_v1';
const CURRENCIES=[['USA','USD'],['EUR','EUR'],['MXC','MXC'],['CAD','CAD'],['REAL','REAL']];
const NEXUS_LOGO='<img class="nexus-app-logo" src="./app-icon.svg?v=nexus-consulta-20260817" alt="Nexus Consulta">';

let docs=[];
let state={view:'home',current:null,loading:false,query:null,filters:{}};

function loadDocs(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');docs=Array.isArray(saved)?saved.map(d=>({...d,name:String(d?.name||'').trim(),locked:!!d?.locked})):[];}catch(e){docs=[];}}
function saveDocs(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(docs));}catch(e){}}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function money(n){return Number(n||0).toLocaleString('es-MX',{maximumFractionDigits:2});}
function rounded(n){return Math.round((Number(n||0)+Number.EPSILON)*100)/100;}
function extractId(url){const m=String(url||'').match(/\/spreadsheets\/d\/([a-zA-Z0-9-_]+)/);return m?m[1]:'';}
function parseAmount(v){if(typeof v==='number')return Number.isFinite(v)?v:0;let s=String(v??'').trim().replace(/\s/g,'').replace(/[^0-9,.-]/g,'');if(!s)return 0;if(s.includes(',')&&s.includes('.'))s=s.lastIndexOf(',')>s.lastIndexOf('.')?s.replace(/\./g,'').replace(',','.'):s.replace(/,/g,'');else if(s.includes(',')){const p=s.split(',');s=(p.length===2&&p[1].length<=2)?p[0].replace(/\./g,'')+'.'+p[1]:s.replace(/,/g,'');}const n=Number(s);return Number.isFinite(n)?n:0;}
function parseDateDMY(v){const p=String(v||'').trim().split('/');if(p.length!==3)return null;const d=+p[0],m=+p[1],y=+p[2];if(!d||!m||!y)return null;const dt=new Date(y,m-1,d);return Number.isNaN(dt.getTime())?null:dt;}
function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(q){if(c==='"'&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')q=false;else cell+=c;}else{if(c==='"')q=true;else if(c===','){row.push(cell);cell='';}else if(c==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell='';}else cell+=c;}}if(cell.length||row.length){row.push(cell.replace(/\r$/,''));rows.push(row);}return rows;}
function checkboxValueIsChecked(v){if(v===true||v===1)return true;if(v===false||v===0||v==null)return false;const s=String(v).trim().toLocaleUpperCase('es-MX');return s==='TRUE'||s==='VERDADERO'||s==='1'||s==='SI'||s==='SÍ';}
function isHtmlOrLogin(text,type=''){return type.includes('text/html')||/<!doctype html|<html/i.test(text)||/sign in|iniciar sesi[oó]n|request access|solicitar acceso/i.test(text);}
async function timedFetch(url,options={},timeoutMs=18000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{return await fetch(url,{...options,signal:controller.signal});}catch(e){if(e?.name==='AbortError')throw new Error('El documento tardó demasiado en responder');throw e;}finally{clearTimeout(timer);}}
async function spreadsheetIsPublic(url){const id=extractId(url);if(!id)return false;try{const endpoint='https://docs.google.com/spreadsheets/d/'+encodeURIComponent(id)+'/gviz/tq?tqx=out:json&headers=0&range=A1:A1&_='+Date.now();const r=await timedFetch(endpoint,{cache:'no-store'},10000);if(!r.ok)return false;const type=(r.headers.get('content-type')||'').toLowerCase(),text=await r.text();if(isHtmlOrLogin(text,type))return false;const start=text.indexOf('{'),end=text.lastIndexOf('}');if(start<0||end<=start)return false;const payload=JSON.parse(text.slice(start,end+1));return !payload.status||payload.status==='ok';}catch(e){return false;}}
async function fetchSheetRows(doc,sheet){const id=extractId(doc.url);if(!id)throw new Error('Enlace no válido');const url='https://docs.google.com/spreadsheets/d/'+encodeURIComponent(id)+'/gviz/tq?tqx=out:csv&sheet='+encodeURIComponent(sheet)+'&range=A:D&_='+Date.now();const r=await timedFetch(url,{cache:'no-store'},22000);if(!r.ok)throw new Error('Google respondió '+r.status);const type=(r.headers.get('content-type')||'').toLowerCase(),text=await r.text();if(isHtmlOrLogin(text,type))throw new Error('El documento no tiene acceso por enlace');return parseCSV(text);}
async function readSheetU1(doc,sheet){const id=extractId(doc.url);const url='https://docs.google.com/spreadsheets/d/'+encodeURIComponent(id)+'/gviz/tq?tqx=out:csv&headers=0&range=U1:U1&sheet='+encodeURIComponent(sheet)+'&_='+Date.now();const r=await timedFetch(url,{cache:'no-store'},10000);if(!r.ok)throw new Error('No se pudo comprobar U1 de '+sheet);const type=(r.headers.get('content-type')||'').toLowerCase(),text=await r.text();if(isHtmlOrLogin(text,type))throw new Error('El documento no tiene acceso mediante vínculo');return checkboxValueIsChecked(parseCSV(text)?.[0]?.[0]);}
async function mapLimit(items,limit,fn){const result=new Array(items.length);let cursor=0;async function worker(){while(true){const i=cursor++;if(i>=items.length)return;result[i]=await fn(items[i],i);}}await Promise.all(Array.from({length:Math.min(limit,items.length||1)},worker));return result;}
async function discoverActiveSheets(doc){const id=extractId(doc.url);if(!id)throw new Error('Enlace no válido');if(!window.XLSX)throw new Error('No se pudo cargar el lector de Google Sheets');const exportUrl='https://docs.google.com/spreadsheets/d/'+encodeURIComponent(id)+'/export?format=xlsx&_='+Date.now();const response=await timedFetch(exportUrl,{cache:'no-store'},25000);if(!response.ok)throw new Error('No se pudo leer la estructura del documento');const type=(response.headers.get('content-type')||'').toLowerCase();if(type.includes('text/html'))throw new Error('El documento no tiene acceso mediante vínculo');let workbook;try{workbook=XLSX.read(await response.arrayBuffer(),{bookSheets:true,bookProps:false});}catch(e){throw new Error('No se pudo leer la lista de hojas del documento');}const names=Array.isArray(workbook.SheetNames)?workbook.SheetNames:[];const checks=await mapLimit(names,8,async name=>{try{return {name,enabled:await readSheetU1(doc,name)};}catch(e){return {name,enabled:false,error:e};}});if(names.length&&checks.every(x=>x.error))throw checks[0].error||new Error('No se pudieron comprobar las hojas del documento');return checks.filter(x=>x.enabled).map(x=>x.name);}

function defaultFilter(docId){if(!state.filters[docId]){const now=new Date(),y=now.getFullYear(),m=String(now.getMonth()+1).padStart(2,'0'),last=String(new Date(y,now.getMonth()+1,0).getDate()).padStart(2,'0');state.filters[docId]={from:`${y}-${m}-01`,to:`${y}-${m}-${last}`};}return state.filters[docId];}
function syncFilterInputs(){const d=state.current;if(!d)return null;const f=defaultFilter(d.id);for(const id of ['from','to']){const el=document.getElementById(id);if(el)f[id]=el.value;}return f;}

async function runQuery(){const d=state.current,f=syncFilterInputs();if(!d||!f)return;if(!f.from||!f.to){alert('Selecciona las dos fechas.');return;}const start=new Date(f.from+'T00:00:00'),end=new Date(f.to+'T23:59:59');if(start>end){alert('La fecha inicial no puede ser posterior a la fecha final.');return;}state.loading=true;state.query=null;render();try{const sheets=await discoverActiveSheets(d);const results=await mapLimit(sheets,4,async sheet=>{try{const rows=await fetchSheetRows(d,sheet);let inherited=null;const totals={USA:0,EUR:0,MXC:0,CAD:0,REAL:0};let operations=0;for(const row of rows){const detected=parseDateDMY(row[0]);if(detected)inherited=String(row[0]).trim();if(!inherited)continue;const date=parseDateDMY(inherited);if(!date||date<start||date>end)continue;const code=String(row[1]||'').trim().toUpperCase(),raw=row[2];if(!Object.prototype.hasOwnProperty.call(totals,code)||raw==null||String(raw).trim()==='')continue;totals[code]+=parseAmount(raw);operations++;}Object.keys(totals).forEach(k=>totals[k]=rounded(totals[k]));return {sheet,totals,operations};}catch(e){return {sheet,error:e?.message||String(e),totals:{USA:0,EUR:0,MXC:0,CAD:0,REAL:0},operations:0};}});const grand={USA:0,EUR:0,MXC:0,CAD:0,REAL:0};let operations=0;for(const r of results){operations+=r.operations||0;for(const [code] of CURRENCIES)grand[code]+=r.totals?.[code]||0;}Object.keys(grand).forEach(k=>grand[k]=rounded(grand[k]));state.query={from:f.from,to:f.to,rows:results,totals:grand,operations};}catch(e){alert('No se pudo consultar el Spreadsheet. '+(e?.message||e));}finally{state.loading=false;render();}}

function route(view,docId,push=true){const doc=docId?docs.find(d=>d.id===docId):null;state.view=view;state.current=doc||null;if(view!=='query')state.query=null;if(push)history.pushState({nexus:true,view,docId:doc?.id||null},'',location.href);render();}
function goHome(){state.view='home';state.current=null;state.query=null;history.pushState({nexus:true,view:'home',docId:null},'',location.href);render();}
function applyHistory(h){const view=h?.nexus?h.view:'home',doc=h?.docId?docs.find(d=>d.id===h.docId):null;state.view=doc||['home','add'].includes(view)?view:'home';state.current=doc||null;state.query=null;render();}

function lockIcon(locked){return locked?'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 10V7a5 5 0 0 1 10 0v3"/><rect x="5" y="10" width="14" height="11" rx="3"/><path d="M12 14v3"/></svg>':'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 10V7a5 5 0 0 1 9.6-2"/><rect x="5" y="10" width="14" height="11" rx="3"/><path d="M12 14v3"/></svg>';}
function lockButton(doc){const locked=!!doc.locked,label=locked?'Bloqueado':'Abierto';return '<button class="doc-lock '+(locked?'is-locked':'is-unlocked')+'" data-doc-lock="'+esc(doc.id)+'" type="button"><span class="doc-lock-icon">'+lockIcon(locked)+'</span><span class="doc-lock-label">'+label+'</span></button>';}
function homeHtml(){const cards=docs.length?'<div class="docs-grid">'+docs.map(doc=>'<article class="doc-card '+(doc.locked?'doc-card-locked':'')+'" data-open="'+esc(doc.id)+'">'+lockButton(doc)+'<div class="doc-top"><div class="doc-title-wrap"><h3 class="doc-title">'+esc(doc.name)+'</h3><div class="doc-kicker"><span class="dot"></span><span>Consulta de operaciones</span></div></div></div><div class="query-card-home"><div class="query-home-icon">⌕</div><div><strong>Consultar documento</strong><span>Filtra un período y revisa todas las hojas y monedas en una sola tabla.</span></div></div><div class="card-foot"><span>'+(doc.locked?'Documento bloqueado':'Listo para consultar')+'</span><span>•••</span></div></article>').join('')+'</div>':'<div class="empty"><div class="empty-icon">⌕</div><h2>Aún no hay documentos</h2><p>Agrega tu primer Google Spreadsheet para consultar todas sus hojas y monedas por fecha.</p><button class="btn btn-add" id="emptyAddBtn"><span class="add-icon">+</span><span class="add-label">Agregar documento</span></button></div>';return '<div class="app-shell"><header class="hero"><div class="hero-inner"><div class="brand"><div class="brand-mark brand-mark-logo">'+NEXUS_LOGO+'</div><div class="brand-copy"><h1>Nexus Consulta</h1><p>Consulta consolidada de operaciones</p></div></div><button class="btn btn-add" id="addBtn"><span class="add-icon">+</span><span class="add-label">Agregar documento</span></button></div></header><main class="main"><div class="section-head"><h2 class="section-title">Documentos</h2></div>'+cards+'</main></div>';}
function addModalHtml(){return '<div class="modal-bg" id="modalBg"><div class="modal-card"><div class="modal-head"><h2>Agregar documento</h2><button class="btn-icon" data-close>×</button></div><div class="field"><label>Nombre</label><input id="docName" placeholder="Nombre" autocapitalize="sentences"></div><div class="field"><label>Enlace de Google Sheets</label><input id="docUrl" placeholder="Pega aquí el enlace de Google Sheets"></div><div class="modal-actions"><button class="btn btn-soft" data-close>Cancelar</button><button class="btn btn-blue" id="saveBtn">Guardar</button></div></div></div>';}
function editModalHtml(){const d=state.current;return '<div class="modal-bg" id="modalBg"><div class="modal-card"><div class="modal-head"><h2>Editar documento</h2><button class="btn-icon" data-close>×</button></div><div class="field"><label>Nombre</label><input id="editName" value="'+esc(d?.name||'')+'"></div><div class="field"><label>Enlace de Google Sheets</label><input id="editUrl" value="'+esc(d?.url||'')+'"></div><div class="modal-actions"><button class="btn btn-soft" data-close>Cancelar</button><button class="btn btn-blue" id="saveEditBtn">Guardar cambios</button></div></div></div>';}
function menuHtml(){const d=state.current;if(!d)return '';return '<div class="sheet-bg" id="sheetBg"><div class="bottom-sheet"><div class="sheet-handle"></div><div class="sheet-title"><h3>'+esc(d.name)+'</h3><p>Selecciona una opción</p></div><button class="sheet-option" data-action="edit"><span class="sheet-icon">✎</span><span><strong>Editar</strong><span>Cambiar nombre o enlace del documento</span></span></button><button class="sheet-option" data-action="query"><span class="sheet-icon">⌕</span><span><strong>Consulta</strong><span>Filtrar todas las hojas y monedas por fecha</span></span></button><button class="sheet-option danger" data-action="delete"><span class="sheet-icon">⌫</span><span><strong>Eliminar</strong><span>Quitar este documento del dispositivo</span></span></button></div></div>';}
function deleteConfirmHtml(){const d=state.current;if(!d)return '';return '<div class="modal-bg" id="deleteConfirmBg"><div class="modal-card delete-confirm-card"><div class="delete-confirm-icon">⌫</div><h2>Eliminar documento</h2><p>¿Seguro que quieres eliminar <strong>'+esc(d.name)+'</strong> de este dispositivo?</p><div class="modal-actions"><button class="btn btn-soft" data-close>Cancelar</button><button class="btn btn-danger" id="confirmDeleteBtn">Eliminar</button></div></div></div>';}
function overlayHtml(){if(state.view==='add')return addModalHtml();if(state.view==='menu')return menuHtml();if(state.view==='edit')return editModalHtml();if(state.view==='delete-confirm')return deleteConfirmHtml();return '';}
function pageHeader(){const d=state.current;return '<header class="detail-hero"><div class="detail-inner"><div class="back" id="backBtn">← Atrás</div><div class="detail-title"><div class="brand-mark brand-mark-logo">'+NEXUS_LOGO+'</div><div><h1>'+esc(d?.name||'')+'</h1><p>Consulta consolidada por fecha</p></div></div></div></header>';}
function queryTableHtml(q){if(!q)return '';const headers=CURRENCIES.map(([,label])=>'<th>'+label+'</th>').join('');const rows=q.rows.length?q.rows.map(r=>'<tr><td class="worker-name">'+esc(r.sheet)+(r.error?'<div class="status-error" style="font-size:10px;font-weight:500;margin-top:3px">No se pudo leer</div>':'')+'</td>'+CURRENCIES.map(([code])=>'<td>'+money(r.totals?.[code]||0)+'</td>').join('')+'<td>'+Number(r.operations||0)+'</td></tr>').join(''):'<tr><td colspan="7">No hay hojas activas.</td></tr>';return '<div class="query-summary"><div><span>PERÍODO</span><strong>'+esc(q.from)+' → '+esc(q.to)+'</strong></div><div><span>OPERACIONES</span><strong>'+q.operations+'</strong></div></div><div class="table-wrap"><table><thead><tr><th>Hoja</th>'+headers+'<th>Ops.</th></tr></thead><tbody>'+rows+'<tr class="query-total-row"><td>TOTAL</td>'+CURRENCIES.map(([code])=>'<td>'+money(q.totals[code]||0)+'</td>').join('')+'<td>'+q.operations+'</td></tr></tbody></table></div>';}
function queryPageHtml(){const d=state.current;if(!d)return homeHtml();const f=defaultFilter(d.id);return '<div class="app-shell">'+pageHeader()+'<main class="main"><div class="filters-card query-only-card"><div class="query-date-grid"><div class="field"><label>Fecha inicial</label><input id="from" type="date" value="'+esc(f.from)+'"></div><div class="field"><label>Fecha final</label><input id="to" type="date" value="'+esc(f.to)+'"></div><button class="btn btn-blue filter-action" id="filterBtn" '+(state.loading?'disabled':'')+'>'+(state.loading?'Consultando…':'Filtrar')+'</button></div>'+(state.loading?'<div class="loading-block">Leyendo hojas activas y calculando todas las monedas…</div>':queryTableHtml(state.query))+'</div></main></div>';}
function render(){const app=document.getElementById('app');if(!app)return;if(['home','add','menu','edit','delete-confirm'].includes(state.view))app.innerHTML=homeHtml()+overlayHtml();else app.innerHTML=queryPageHtml();}
function showPublicAccessWarning(){alert('No se puede leer el documento. Activa: Compartir → Acceso general → Cualquier persona con el vínculo → Lector.');}

document.addEventListener('click',async e=>{const t=e.target;if(t.id==='addBtn'||t.id==='emptyAddBtn'){state.view='add';history.pushState({nexus:true,view:'add'},'',location.href);render();return;}if(t.matches('[data-close]')||t.id==='modalBg'||t.id==='sheetBg'){if((t.id==='modalBg'||t.id==='sheetBg')&&e.target!==t)return;history.back();return;}const lock=t.closest('[data-doc-lock]');if(lock){e.stopPropagation();const d=docs.find(x=>x.id===lock.dataset.docLock);if(d){d.locked=!d.locked;saveDocs();render();}return;}const card=t.closest('[data-open]');if(card){route('menu',card.dataset.open,true);return;}const action=t.closest('[data-action]')?.dataset.action;if(action){const id=state.current?.id;if(action==='edit')route('edit',id,true);else if(action==='query'){if(state.current?.locked){alert('Desbloquea el documento para consultarlo.');return;}route('query',id,true);}else if(action==='delete')route('delete-confirm',id,true);return;}if(t.id==='backBtn'){history.back();return;}if(t.id==='filterBtn'){runQuery();return;}if(t.id==='saveBtn'){const name=document.getElementById('docName')?.value.trim(),url=document.getElementById('docUrl')?.value.trim();if(!name||!extractId(url)){alert('Escribe un nombre y un enlace válido de Google Sheets.');return;}t.disabled=true;t.textContent='Validando…';const ok=await spreadsheetIsPublic(url);if(!ok){t.disabled=false;t.textContent='Guardar';showPublicAccessWarning();return;}docs.push({id:'d'+Date.now(),name:name.charAt(0).toUpperCase()+name.slice(1),url,locked:false});saveDocs();goHome();return;}if(t.id==='saveEditBtn'){const name=document.getElementById('editName')?.value.trim(),url=document.getElementById('editUrl')?.value.trim();if(!name||!extractId(url)){alert('Completa los datos correctamente.');return;}const d=state.current;if(!d)return;t.disabled=true;t.textContent='Validando…';const ok=await spreadsheetIsPublic(url);if(!ok){t.disabled=false;t.textContent='Guardar cambios';showPublicAccessWarning();return;}d.name=name.charAt(0).toUpperCase()+name.slice(1);d.url=url;saveDocs();goHome();return;}if(t.id==='confirmDeleteBtn'){const id=state.current?.id;docs=docs.filter(d=>d.id!==id);saveDocs();goHome();return;}});
window.addEventListener('popstate',e=>applyHistory(e.state));

loadDocs();
history.replaceState({nexus:true,view:'home',docId:null},'',location.href);
render();
