-- NEXUS Versión 1 - Supabase/PostgreSQL
-- Ejecutar en Supabase → SQL Editor → New query → Run

create table if not exists public.nexus_meta (
  team_id text primary key,
  users jsonb not null default '[]'::jsonb,
  settings jsonb not null default '{}'::jsonb,
  disabled_tables jsonb not null default '[]'::jsonb,
  reset_version text default 'version_1_supabase',
  version_label text default 'Versión 1',
  updated_at timestamptz default now()
);

create table if not exists public.nexus_records (
  team_id text not null,
  id text not null,
  account text default '',
  currency text default 'CUP',
  date text default '',
  entry numeric default 0,
  exit numeric default 0,
  description text default '',
  confirmed boolean default false,
  count boolean default false,
  payload jsonb not null default '{}'::jsonb,
  deleted boolean default false,
  deleted_at timestamptz,
  updated_at_client timestamptz,
  updated_at timestamptz default now(),
  client_id text default '',
  op_id text,
  primary key (team_id, id)
);

create table if not exists public.nexus_audit (
  audit_id bigint generated by default as identity primary key,
  team_id text not null,
  op_id text,
  record_id text,
  type text,
  username text,
  device_id text,
  account text,
  currency text,
  date text,
  method text default 'supabase-pwa',
  status text default 'ok',
  payload jsonb default '{}'::jsonb,
  client_time timestamptz,
  created_at timestamptz default now()
);

create index if not exists nexus_records_team_updated_idx on public.nexus_records(team_id, updated_at);
create index if not exists nexus_records_team_account_currency_idx on public.nexus_records(team_id, account, currency);
create index if not exists nexus_audit_team_created_idx on public.nexus_audit(team_id, created_at);

-- Prueba rápida: RLS desactivado, equivalente a reglas abiertas de Firebase.
alter table public.nexus_meta disable row level security;
alter table public.nexus_records disable row level security;
alter table public.nexus_audit disable row level security;

insert into public.nexus_meta(team_id, users, settings, disabled_tables, reset_version, version_label)
values (
  'equipo_principal',
  '[{"username":"admin","password":"1234","role":"administrador","account":""}]'::jsonb,
  '{"appearance":"light","fontSize":"normal","coverageQty":1,"coverageUnit":"dia","avgQty":30,"avgUnit":"dia","lookbackDays":30}'::jsonb,
  '[]'::jsonb,
  'version_1_supabase',
  'Versión 1'
)
on conflict (team_id) do nothing;

do $$
begin
  begin
    alter publication supabase_realtime add table public.nexus_meta;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.nexus_records;
  exception when duplicate_object then null;
  end;
end $$;
